# Generated by Django 4.0 on 2025-03-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
    ]
