# Generated by Django 4.0 on 2025-03-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_country_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaRule',
        ),
    ]
